# Generated by Django 5.0.1 on 2024-03-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('tel_number', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
